spring:
  application:
    name: big-event

  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 123456

#开启驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true

alioss:
  endpoint: https://oss-cn-hangzhou.aliyuncs.com
  bucket-name: my-bucket-unique-20250101